http:
  routers:
    nosignal-api:
      rule: Host(`api.nosignal.site`)
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: nosignal-api

    nosignal-frontend:
      rule: Host(`nosignal.site`)
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: nosignal-frontend

  services:
    nosignal-api:
      loadBalancer:
        servers:
          - url: http://nosignal-backend:8000

    nosignal-frontend:
      loadBalancer:
        servers:
          - url: http://nosignal-frontend:80
